// import express from 'express';
import express = require('express');
import {config} from '../config/config.js';
import { Mongodb } from "./common/mongodb/mongodb";
import { UserRouter } from "./routers/userRouter";
import swaggerUi from 'swagger-ui-express';
const swaggerJsdoc = require("swagger-jsdoc");
const app = express();

const allowCrossDomain = (req:any, res:any, next:any) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
  res.header('Access-Control-Allow-Headers', "Content-Type, authorization");
  next();
}

const mongo = new Mongodb(config.mongodb.url,config.mongodb.dbName);

app.use( (req, res, next) => {
  res.locals.mongo = mongo
  next()
})

// Swagger UI
const opt = {
  customSiteTitle: "PES API Guid",
  customCss:".swagger-ui .topbar {background-color:  #895659}"
  // customfavIcon: "./images/favicon-32x32.png",
}
const options = {
  swaggerDefinition: {
      openapi: '3.0.1',
      // Like the one described here: https://swagger.io/specification/#infoObject
      info: {
        title: "Hungry API",
        version: "1.0.0",
        description: "Hungry API with autogenerated swagger doc",
      },
      host: "localhost",
      basePath: "/",
      produces: ["application/json"],

      security: [
        { bearerAuth: [] },
      ],
    },
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ["**/*.ts"],
  };
  const specs = swaggerJsdoc(options);

 app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs, opt));

app.get("/swagger.json", (req, res) => {
  res.setHeader("Content-Type", "application/json");
  res.send(specs);
});

const userRouter = new UserRouter();
app.use("/api/v1/user/", userRouter.userRoute);

async function main() {
  try {
    await mongo.init();
    // Start server
    app.listen(config.PORT, async () => {
      console.log(`Server is listning in port ${config.PORT}`);
    });
  } catch (er) {
    console.log("error:" + er);
    return er;
  }
}

main();

